export interface School {
  name: string;
  location: string;
  dept: string;
  region: 'all' | 'bogota_cundinamarca' | 'santanderes' | 'caribe' | 'antioquia_eje' | 'llanos_amazonia' | 'centro';
  file: string;
}

export const REGIONS = [
  { id: 'all', label: 'Todos (+60)' },
  { id: 'bogota_cundinamarca', label: 'Bogotá y Cundinamarca' },
  { id: 'santanderes', label: 'Santanderes' },
  { id: 'caribe', label: 'Caribe' },
  { id: 'antioquia_eje', label: 'Antioquia y Eje Cafetero' },
  { id: 'llanos_amazonia', label: 'Llanos y Amazonía' },
  { id: 'centro', label: 'Centro y Sur' },
] as const;

export const SCHOOLS_DATA: School[] = [
  { name: "CC Presentación Buenahora", location: "Piedecuesta", dept: "Santander", region: "santanderes", file: "cc-presentacion-buenahora-simulacros.webp" },
  { name: "Colegio Prado Veraniego", location: "Suba", dept: "Bogotá D.C.", region: "bogota_cundinamarca", file: "colegio-colegio-prado-veraniego-suba-bogota-veraniego-suba-bogota.webp" },
  { name: "Colegio Integrado Monseñor Evaristo Blanco", location: "San Miguel", dept: "Santander", region: "santanderes", file: "colegio-integrado-monsenor-evaristo-blanco-san-miguel-santander.webp" },
  { name: "Colegio Integrado Simón Bolívar", location: "Cúcuta", dept: "Norte de Santander", region: "santanderes", file: "colegio-integrado-simon-bolivar-cucuta-n-de-santander.webp" },
  { name: "Colegio Nuestra Señora De Nazareth", location: "Purificación", dept: "Tolima", region: "centro", file: "colegio-nuestra-senora-de-nazareth-purificacion-tolima.webp" },
  { name: "Colegio Santa María Del Rosario", location: "Medellín", dept: "Antioquia", region: "antioquia_eje", file: "colegio-santa-maria-del-rosario-medellin-antioquia.webp" },
  { name: "Colegio Villemar Del Carmen", location: "Fontibón", dept: "Bogotá D.C.", region: "bogota_cundinamarca", file: "colegio-villemar-del-carmen-fontibon-bogota.webp" },
  { name: "Corporación Educativa Colegio Comunal Mixto", location: "Barranquilla", dept: "Atlántico", region: "caribe", file: "corporacion-educativa-colegio-comunal-mixto-barranquilla-atlantico.webp" },
  { name: "Escuela Normal Superior De Piedecuesta", location: "Piedecuesta", dept: "Santander", region: "santanderes", file: "escuela-normal-superior-de-piedecuesta-piedecuesta-santander.webp" },
  { name: "Escuela Superior Monterrey", location: "Monterrey", dept: "Casanare", region: "llanos_amazonia", file: "escuela-superior-monterrey-simulacros.webp" },
  { name: "IE Alegaxu", location: "Alegaxu", dept: "Casanare", region: "llanos_amazonia", file: "ie-alegaxu-simulacros.webp" },
  { name: "IE Alfonso López", location: "Cúcuta", dept: "Norte de Santander", region: "santanderes", file: "ie-alfonso-lopez-simulacros.webp" },
  { name: "IE Antonio Martínez Delgado", location: "Hato Corozal", dept: "Casanare", region: "llanos_amazonia", file: "ie-antonio-martinez-delgado-simulacros.webp" },
  { name: "IE Buenos Aires", location: "Buenos Aires", dept: "Casanare", region: "llanos_amazonia", file: "ie-buenos-aires-simulacros.webp" },
  { name: "IE Camilo Torres Restrepo", location: "Barrancabermeja", dept: "Santander", region: "santanderes", file: "ie-camilo-torres-restrepo-simulacros.webp" },
  { name: "IE Cazucá", location: "Soacha", dept: "Cundinamarca", region: "bogota_cundinamarca", file: "ie-cazuca-simulacros.webp" },
  { name: "IE Ciudad Latina", location: "Soacha", dept: "Cundinamarca", region: "bogota_cundinamarca", file: "ie-ciudad-latina-simulacros.webp" },
  { name: "IE Ciudadela Sucre", location: "Soacha", dept: "Cundinamarca", region: "bogota_cundinamarca", file: "ie-ciudadela-sucre-simulacros.webp" },
  { name: "IE Gabriel García Márquez", location: "Floridablanca", dept: "Santander", region: "santanderes", file: "ie-gabriel-garcia-marquez-simulacros.webp" },
  { name: "IE Gaviotas", location: "Maní", dept: "Casanare", region: "llanos_amazonia", file: "ie-gaviotas-simulacros.webp" },
  { name: "IE Jorge Gaitán", location: "Aguazul", dept: "Casanare", region: "llanos_amazonia", file: "ie-jorge-gaitan-simulacros.webp" },
  { name: "IE La Despensa", location: "Soacha", dept: "Cundinamarca", region: "bogota_cundinamarca", file: "ie-la-despensa-simulacros.webp" },
  { name: "IE Las Villas", location: "Soacha", dept: "Cundinamarca", region: "bogota_cundinamarca", file: "ie-las-villas-simulacros.webp" },
  { name: "IE Luis Carlos Galán", location: "Cúcuta", dept: "Norte de Santander", region: "santanderes", file: "ie-luis-carlos-galan-simulacros.webp" },
  { name: "IE Luis Gabriel Carlos", location: "Piedecuesta", dept: "Santander", region: "santanderes", file: "ie-luis-gabriel-carlos-simulacros.webp" },
  { name: "IE Luis Hernández Vargas", location: "Hato Corozal", dept: "Casanare", region: "llanos_amazonia", file: "ie-luis-hernandez-vargas-simulacros.webp" },
  { name: "IE Luis María Jiménez", location: "Aguazul", dept: "Casanare", region: "llanos_amazonia", file: "ie-luis-maria-jimenez-simulacros.webp" },
  { name: "IE Pedro De Heredia", location: "Cartagena", dept: "Bolívar", region: "caribe", file: "ie-pedro-de-heredia-simulacros.webp" },
  { name: "IE Rafael Uribe Uribe", location: "Cúcuta", dept: "Norte de Santander", region: "santanderes", file: "ie-rafael-uribe-uribe-simulacros.webp" },
  { name: "IE Remedios Solano", location: "Barrancas", dept: "La Guajira", region: "caribe", file: "ie-remedios-solano-simulacros.webp" },
  { name: "IE Sagrado Corazón", location: "Soacha", dept: "Cundinamarca", region: "bogota_cundinamarca", file: "ie-sagrado-corazon-simulacros.webp" },
  { name: "IE Salvador Camacho", location: "Nunchía", dept: "Casanare", region: "llanos_amazonia", file: "ie-salvador-camacho-simulacros.webp" },
  { name: "IE San Gerardo", location: "San Gerardo", dept: "Santander", region: "santanderes", file: "ie-san-gerardo-simulacros.webp" },
  { name: "IE Siglo XXI", location: "Tauramena", dept: "Casanare", region: "llanos_amazonia", file: "ie-siglo-xxi-simulacros.webp" },
  { name: "IE Simón Bolívar", location: "Soracá", dept: "Boyacá", region: "centro", file: "ie-simon-bolivar-simulacros.webp" },
  { name: "IED Reino De Holanda", location: "Tunjuelito", dept: "Bogotá D.C.", region: "bogota_cundinamarca", file: "ied-reino-de-holanda-tuenjelito-bogota.webp" },
  { name: "IERD La Fuente", location: "Tocancipá", dept: "Cundinamarca", region: "bogota_cundinamarca", file: "ierd-la-fuente-simulacros.webp" },
  { name: "IET Integrado", location: "Socha", dept: "Boyacá", region: "centro", file: "iet-integrado-simulacros.webp" },
  { name: "IETAC", location: "Aguazul", dept: "Casanare", region: "llanos_amazonia", file: "ietac-simulacros.webp" },
  { name: "IE Alonso Carvajal Peralta", location: "Chitagá", dept: "Norte de Santander", region: "santanderes", file: "institucion-educativa-alonso-carvajal-peralta-chitaga-n-de-santander.webp" },
  { name: "IE Bernardo Uribe Londoño", location: "La Ceja", dept: "Antioquia", region: "antioquia_eje", file: "institucion-educativa-bernardo-uribe-londono-la-ceja-del-tambo-antioquia.webp" },
  { name: "IE Bonifacio Gutiérrez", location: "Hato Corozal", dept: "Casanare", region: "llanos_amazonia", file: "institucion-educativa-bonifacio-gutierrez-hato-corozal-casanare.webp" },
  { name: "IE Cupiagua", location: "Aguazul", dept: "Casanare", region: "llanos_amazonia", file: "institucion-educativa-cupiagua-aguazul-casanare.webp" },
  { name: "IE Custodio García Rovira", location: "Inírida", dept: "Guainía", region: "llanos_amazonia", file: "institucion-educativa-custodio-garcia-rovira-inirida-guainia.webp" },
  { name: "IED Loma Del Bálsamo", location: "Algarrobo", dept: "Magdalena", region: "caribe", file: "institucion-educativa-departalmental-loma-del-balsamo-algarrobo-magdalena.webp" },
  { name: "IED Caño De Aguas", location: "Sitio Nuevo", dept: "Magdalena", region: "caribe", file: "institucion-educativa-departamental-cano-de-aguas-cano-de-aguas-magdalena.webp" },
  { name: "IED Desarrollo Rural", location: "Fósca", dept: "Cundinamarca", region: "bogota_cundinamarca", file: "institucion-educativa-departamental-de-desarrollo-rural-fosca-cundinamarca.webp" },
  { name: "IED María Medina", location: "Fósca", dept: "Cundinamarca", region: "bogota_cundinamarca", file: "institucion-educativa-departamental-maria-medina-fosca-fosca-cundinamarca.webp" },
  { name: "IED Rural De Palermo", location: "Sitio Nuevo", dept: "Magdalena", region: "caribe", file: "institucion-educativa-departamental-rural-de-palermo-sitio-nuevo-magdalena.webp" },
  { name: "IE El Cusiana", location: "Tauramena", dept: "Casanare", region: "llanos_amazonia", file: "institucion-educativa-el-cusiana-tauramena-casanare.webp" },
  { name: "IE Enrique Olaya Herrera", location: "Armenia", dept: "Quindío", region: "antioquia_eje", file: "institucion-educativa-enrique-olaya-herrera-armenia-quindio.webp" },
  { name: "IE Horacio Perdomo", location: "Hato Corozal", dept: "Casanare", region: "llanos_amazonia", file: "institucion-educativa-horario-perdomo-hato-corozal-casanare.webp" },
  { name: "IE Jaime Garzón", location: "Cúcuta", dept: "Norte de Santander", region: "santanderes", file: "institucion-educativa-jaime-garzon-cucuta-n-de-santander.webp" },
  { name: "IE Jesús Bernal Pinzón", location: "Maní", dept: "Casanare", region: "llanos_amazonia", file: "institucion-educativa-jesus-bernal-pinzon-mani-casanare.webp" },
  { name: "IE La Inmaculada", location: "Orocué", dept: "Casanare", region: "llanos_amazonia", file: "institucion-educativa-la-inmaculada-orocue-casanare.webp" },
  { name: "IE Liceo Alegre Juventud", location: "Malambo", dept: "Atlántico", region: "caribe", file: "institucion-educativa-liceo-alegre-juventud-malambo-atlantico.webp" },
  { name: "IE Los Curos", location: "Piedecuesta", dept: "Santander", region: "santanderes", file: "institucion-educativa-los-curos-piedecuesta-santander.webp" },
  { name: "IE Luis Sánchez Porto", location: "Soledad", dept: "Atlántico", region: "caribe", file: "institucion-educativa-luis-sanchez-porto-soledad-atlantico.webp" },
  { name: "IE Sagrado Corazón De Jesús", location: "Cúcuta", dept: "Norte de Santander", region: "santanderes", file: "institucion-educativa-sagrado-corazon-de-jesus-cucuta-n-de-santander.webp" },
  { name: "IE San Agustín", location: "Aguazul", dept: "Casanare", region: "llanos_amazonia", file: "institucion-educativa-san-agustin-aguazul-casanare.webp" },
  { name: "IE Santa Irene", location: "Trinidad", dept: "Casanare", region: "llanos_amazonia", file: "institucion-educativa-santa-irene-trinidad-casanare.webp" },
  { name: "IET Guataca Sur", location: "Margarita", dept: "Bolívar", region: "caribe", file: "institucion-educativa-tecnica-guataca-sur-margarita-bolivar.webp" },
  { name: "IE Víctor Gómez Corredor", location: "El Tablón", dept: "Casanare", region: "llanos_amazonia", file: "institucion-educativa-victor-gomez-corredor-el-tablon-casanare.webp" },
  { name: "IED Pedro De Heredia", location: "Pedraza", dept: "Magdalena", region: "caribe", file: "institucion-eucativa-departamental-pedro-de-heredia-pedraza-magdalena.webp" },
  { name: "IE Antonio Nariño", location: "Pore", dept: "Casanare", region: "llanos_amazonia", file: "instituto-educativo-antonio-narino-pore-casanare.webp" },
  { name: "Instituto Técnico Nacional De Comercio", location: "Cúcuta", dept: "Norte de Santander", region: "santanderes", file: "instituto-tecnico-nacional-de-comercio-cucuta-norte-de-santander.webp" }
];
